### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by darma-avalos** [teracyhq-incubator/pixelate#12]

**Comment by hoatle** [comment]
@darma-avalos it's not really abandoned, however, we do not have any plan to develop it further at the moment (just bug fixes are accepted now).

We're planning to add keyboard shortcut but it's not ready yet to be merged. Otherwise, no further plan.

Do you have any idea to make it better by suggesting new features?

The current code base is very stable and strong, it works on a real project for several years without any bugs.

**Comment by darma-avalos** [comment]
Hello, thank you for your response. I can't find a way to make it work. The demo page is a 404. Do you have any other URL where I can take a look?

**Comment by hoatle** [comment]
sorry that we haven't get the demo site updated yet, you can follow the following steps to try it.

- You can create a test.html file
- download this https://github.com/teracyhq-incubator/pixelate/blob/develop/app/scripts/pixelate.js and add it to your test.html file
- and use this file https://github.com/teracyhq-incubator/pixelate/blob/develop/app/scripts/main.js for testing (which requires jquery)
- to get https://github.com/teracyhq-incubator/pixelate/blob/develop/app/scripts/main.js#L47-L57 works, you need to create <canvas id="main-canvas"></canvas> and don't forget to use the valid working image url
- to get https://github.com/teracyhq-incubator/pixelate/blob/develop/app/scripts/main.js#L59 works, you need to provide the valid working image url
- to get https://github.com/teracyhq-incubator/pixelate/blob/develop/app/scripts/main.js#L61 works, you need to provide an image tag with id "img-test" and a valid working image url as "src".

I hope that you can test by following the instruction above.

We'll update the demo page and instruction soon so that you can follow better.

**Comment by darma-avalos** [comment]
Awesome! Thank you very much.

**Comment by datphan** [comment]
@darma-avalos Hello, you can run this demo on your local machine by following this step:

```
$ git clone git@github.com:teracyhq-incubator/pixelate.git
$ cd pixelate/
$ npm install
$ grunt serve
```
Hope this help!

**Comment by darma-avalos** [comment]
HI, thanks but I get a permission denied.

C:\Users\Darma>git clone git@github.com:teracyhq-incubator/pixelate.git
Cloning into 'pixelate'...
Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by datphan** [comment]
@darma-avalos lets try `https://github.com/teracyhq-incubator/pixelate.git` so it looks like this:
```
$ git clone https://github.com/teracyhq-incubator/pixelate.git
$ cd pixelate/
$ npm install
$ grunt serve
```

**Comment by darma-avalos** [comment]
Thank you very much, but no cigar. Such a pity because this is exactly what I am looking for and would save me huge amount of time. I can't manage to get past this. (see my attachment)
Any idea what I am missing. Is there an implementation of this script somewhere that I could take a look at it. I really do not know where to start. Thanks a bunch!
![_______0](https://user-images.githubusercontent.com/10453340/28367083-b7419a6e-6c8f-11e7-9776-d3bcdab99d98.png)

**Comment by hoatle** [comment]
@darma-avalos have you tried @datphan's comment? Let me know if it works for you that way.

**Comment by darma-avalos** [comment]
Hi @hoatle thank you, no it does not work for me. I got via the git installation @datphan kindly sent, about 5000 files, and I had no idea where to start. I installed it as you instructed and I it pixelates a selection but I get an error on the console, and can do anything further. This is probably because I have no idea how to correctly initialize it or use it. That is why I asked if there was a sample somewhere. Thanks a bunch for trying to help me.

**Comment by hoatle** [comment]
@datphan could you provide a simple demo deployment somewhere so that @darma-avalos could look into? it will help him a lot.

**Comment by datphan** [comment]
@darma-avalos the demo is on `app/index.html`, if you do as my instruction above then when you run `grunt serve` it will run it

**Comment by darma-avalos** [comment]
Hi @datphan , Thank you. It does not work for me. I even recreated the demo and downloaded manually one by one all dependencies. It does not work for me. Thank you for trying to help.

**Comment by datphan** [comment]
@darma-avalos I guess based on the images above that you have not include `styles/pixelate.css`, is that correct?

**Comment by darma-avalos** [comment]
@datphan oops that image I uploaded is not correct. Can I send you a link privately so you could see live hwat I did? I would appreciate if you help me get the pxl.select(....) in a way I can load it via something var img    = canvas.toDataURL("image/png"); or ajax? That would help me so much.

**Comment by darma-avalos** [comment]
I got it ! Thank you very much @datphan and @hoatle , I had to puzzle a lot but I got it working. It would be nice to have a demo and a dist package for devs who are not very familiar with git and bower.

It is a great script, thank you very much for sharing it!

**Comment by hoatle** [comment]
yeah, #5 should do that.
